- hosts: all
  tasks:
    - name: "Install the package for me"
      package:
        name: "httpd"
        state: present

    - name: "copy my webpages"
      copy:
        src: index.html
        dest: /var/www/html
        owner: root
   
    - name: "start httpd service"
      service:
        name: httpd
        state: started
        enabled: yes